load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "core_test",
    srcs = ["core_test.cpp"],
    data = [
        "//zfc:axioms.fol",
        "//zfc:axioms.fol.h",
        "//zfc:ordered_pair.fol",
        "//zfc:ordered_pair.fol.h",
    ],
    deps = [
        "//src/core:formula",
        "//src/parser",
    ],
)

cc_test(
    name = "runtime_test",
    srcs = ["runtime_test.cpp"],
    data = [
        "//zfc:axioms.fol",
        "//zfc:axioms.fol.h",
        "//zfc:functions.fol",
        "//zfc:functions.fol.h",
        "//zfc:functions.fol.proof",
        "//zfc:ordered_pair.fol",
        "//zfc:ordered_pair.fol.h",
        "//zfc:ordered_pair.fol.proof",
        "//zfc:replacement_choice.fol",
        "//zfc:replacement_choice.fol.h",
        "//zfc:test.fol",
    ],
    deps = [
        "//src/runtime",
        "//src/parser",
    ],
)

test_suite(
    name = "all_tests",
    tests = [
        ":core_test",
        ":runtime_test",
    ],
)
