load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "core_test",
    srcs = ["core_test.cpp"],
    data = [
        "//zfc/basics:axioms.fol.def",
        "//zfc/basics:ordered_pair.fol.def",
    ],
    deps = [
        "//src/core:formula",
        "//src/parser",
    ],
)

cc_test(
    name = "runtime_test",
    srcs = ["runtime_test.cpp"],
    data = [
        "//zfc/basics:axioms.fol.def",
        "//zfc/basics:functions.fol.def",
        "//zfc/basics:functions.fol.proof",
        "//zfc/basics:ordered_pair.fol.def",
        "//zfc/basics:ordered_pair.fol.proof",
        "//zfc/basics:replacement_choice.fol.def",
    ],
    deps = [
        "//src/runtime",
        "//src/parser",
    ],
)

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "verify_file",
    srcs = ["verify_file.cpp"],
    deps = [
        "//src/runtime",
        "//src/parser",
    ],
)

test_suite(
    name = "all_tests",
    tests = [
        ":core_test",
        ":runtime_test",
    ],
)
