load("//build:fol.bzl", "fol_library", "fol_proof")

fol_library(
    name = "induction_lib",
    header = "induction.fol.def",
    deps = [
        "//zfc/basics:functions",
        "//zfc/basics:subset",
    ],
)

fol_proof(
    name = "induction",
    header = "induction.fol.def",
    proof = "induction.fol.proof",
    deps = [
        "//zfc/basics:functions",
        "//zfc/basics:subset",
    ],
)
