load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "registry",
    hdrs = ["registry.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "logging",
    hdrs = ["logging.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "error",
    hdrs = ["error.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "profiler",
    hdrs = ["profiler.h"],
    strip_include_prefix = "/src/util",
    include_prefix = "src/util",
    visibility = ["//visibility:public"],
)
