cc_library(
    name = "formula",
    srcs = ["formula.cpp"],
    hdrs = ["formula.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/util:registry"],
)

cc_library(
    name = "proof",
    hdrs = ["proof.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":formula",
        "//src/util:registry",
    ],
)
