load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "formula",
    srcs = ["formula.cpp"],
    hdrs = ["formula.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/util:logging",
        "//src/util:registry",
    ],
)

cc_library(
    name = "proof",
    srcs = ["proof.cpp"],
    hdrs = ["proof.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":formula",
        "//src/util:error",
        "//src/util:registry",
    ],
)
