cc_library(
    name = "formula",
    srcs = ["formula.cpp"],
    hdrs = ["formula.h"],
    visibility = ["//visibility:public"],
    deps = ["//src/util:registry"],
)

cc_library(
    name = "proof",
    srcs = ["proof.cpp"],
    hdrs = ["proof.h"],
    visibility = ["//visibility:public"],
    deps = [":formula"],
)

cc_library(
    name = "parser",
    srcs = ["parser.cpp"],
    hdrs = ["parser.h"],
    visibility = ["//visibility:public"],
    deps = [":formula"],
)

cc_library(
    name = "zfc",
    srcs = ["zfc.cpp"],
    hdrs = ["zfc.h"],
    visibility = ["//visibility:public"],
    deps = [":formula"],
)

cc_library(
    name = "prover",
    srcs = ["prover.cpp"],
    hdrs = ["prover.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":formula",
        ":parser",
        ":proof",
    ],
)

cc_library(
    name = "script",
    srcs = ["script.cpp"],
    hdrs = ["script.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":formula",
        ":parser",
        ":prover",
        ":zfc",
    ],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":formula",
        ":parser",
        ":proof",
        ":zfc",
    ],
)

cc_binary(
    name = "run",
    srcs = ["run.cpp"],
    deps = [
        ":script",
    ],
)
