load("//build:fol.bzl", "fol_library", "fol_proof")

fol_library(
    name = "mm_comprehension",
    header = "mm_comprehension.fol.def",
    deps = ["//metamath/bridge:predicate"],
)

fol_proof(
    name = "mm_batch_000",
    header = "mm_batch_000.fol.def",
    proof = "mm_batch_000.fol.proof",
    deps = [":mm_comprehension"],
)

fol_proof(
    name = "mm_batch_001",
    header = "mm_batch_001.fol.def",
    proof = "mm_batch_001.fol.proof",
    deps = [":mm_batch_000"],
)

fol_proof(
    name = "mm_batch_002",
    header = "mm_batch_002.fol.def",
    proof = "mm_batch_002.fol.proof",
    deps = [":mm_batch_001"],
)

fol_proof(
    name = "mm_batch_003",
    header = "mm_batch_003.fol.def",
    proof = "mm_batch_003.fol.proof",
    deps = [":mm_batch_002"],
)

fol_proof(
    name = "mm_batch_004",
    header = "mm_batch_004.fol.def",
    proof = "mm_batch_004.fol.proof",
    deps = [":mm_batch_003"],
)

